In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df=pd.read_csv('D:\Python Projects\hiring.csv')

In [3]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [4]:
import math
test_score_median=math.floor(df.test_score.median())

In [5]:
test_score_median

8

In [6]:
df.test_score=df.test_score.fillna(test_score_median)

In [7]:
df.experience = df.experience.fillna("zero")

In [8]:
from word2number import w2n
df.experience=df.experience.apply(w2n.word_to_num)

In [9]:
df.experience

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [10]:
reg_obj=linear_model.LinearRegression()
reg_obj.fit(df[['experience','test_score','interview_score']], df.salary)

LinearRegression()

In [11]:
reg_obj.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [12]:
reg_obj.intercept_

17737.26346433768

In [13]:
reg_obj.predict([[2,9,6]])

array([53205.96797671])

In [14]:
reg_obj.predict([[12,10,10]])

array([92002.18340611])

In [15]:
import pickle

In [16]:
with open('model_pickle','wb') as f:
    pickle.dump(reg_obj,f)

In [17]:
with open('model_pickle','rb') as f:
    Hiring_model=pickle.load(f)

In [19]:
Hiring_model.predict([[2,9,6]])

array([53205.96797671])